import CustomHeading from "../CustomHeading";
import {Container, Grid, Stack} from "@mui/material";
import React from "react";
import Project from "./Project";
import {procedural_terrains} from "../../images";
import {cryptology} from "../../images";
import {flashcards} from "../../images";
import {Noto} from "../../images";
import {STORE} from "../../images";

export default function FeaturedProjects({shrink, shrinked}) {
  return (
    <Grid container justifyContent="center">
      <Grid item xs={shrink ? 12 : 10}>
        <Container className="work" sx={{mt: (theme) => theme.spacing(20)}}>
          <Grid container>
            <Grid item xs={12} sm={8}>
              <CustomHeading pre_text="03." text="Some Things I've Built"/>
            </Grid>
          </Grid>
          <Stack rowGap={4} mt={(theme) => theme.spacing(8)}>
            <Project
              shrinked={shrinked}
              title="STOR-E"
              stack={[
                "React",
                "Redux",
                "Chakra-UI",
                "Node JS",
                "Express",
                "MongoDB",
              ]}
              link="https://www.storebyecell.in/"
              image={STORE}
              summary="SGSITS official merchandise store. A practice venture by E-Cell SGSITS"
            />
            <Project
              shrinked={shrinked}
              flipped
              title="Flashcards"
              stack={[
                "React",
                "Redux",
                "Material UI",
                "Node JS",
                "Express",
                "MongoDB",
              ]}
              github="https://github.com/r0nz-29/flashcards"
              link="https://myshare.vercel.app/"
              image={flashcards}
              summary="An application to make notes in the form of flashcards for easy memorization and revision"
            />
            {/*<Project*/}
            {/*  flipped*/}
            {/*  shrinked={shrinked}*/}
            {/*  title="Markdown Editor - Noto"*/}
            {/*  stack={["Java", "JavaFX", "Regular Expressions"]}*/}
            {/*  github="https://github.com/r0nz-29/Noto"*/}
            {/*  image={Noto}*/}
            {/*  summary="A barebones markdown editor built with java. Real-time conversion of markdown into well formatted templates"*/}
            {/*/>*/}
            <Project
              shrinked={shrinked}
              title="Cryptology"
              stack={["React", "Redux", "Material-ui", "RapidAPI"]}
              github="https://github.com/r0nz-29/cryptology"
              link="https://cryptology-29.netlify.app/"
              image={cryptology}
              summary="Get all information and latest news related to cryptocurrencies at one place, along with in depth analysis for each currency"
            />
            <Project
              shrinked={shrinked}
              title="Procedural terrains"
              stack={["React", "three.js", "GLSL", "Shaders"]}
              github="https://github.com/r0nz-29/procedural-terrains"
              link="https://heightmap-terrain.vercel.app/"
              flipped
              image={procedural_terrains}
              summary="Landforms generated by modifying the geometry of a plane using heightmaps and algorithms like perlin noise"
            />
            {/*<Project*/}
            {/*  shrinked={shrinked}*/}
            {/*  title="Rarety.io"*/}
            {/*  stack={["React", "Material UI", "Redux"]}*/}
            {/*  // github="https://github.com/r0nz-29/procedural-terrains"*/}
            {/*  link="https://rarety.io"*/}
            {/*  image={rarety}*/}
            {/*  summary="This is a NFT marketplace which is based on the cardano blockchain. I developed the whole frontend, integrated wallets like Nami wallet, Flint wallet and CCvault, while other teammates developed the backend."*/}
            {/*/>*/}
            {/* <Project
              shrinked={shrinked}
              title="Plan your next trip"
              stack={["React", "Material UI", "Redux", "Java", "Spring-boot"]}
              github="https://github.com/r0nz-29/procedural-terrains"
              link="https://trip-planner-29.netlify.app/"
              flipped
              image={tripPlanner}
              summary="Your next trip is a single click away! Set your preferences and let the app find your next destination."
            /> */}
          </Stack>
        </Container>
      </Grid>
    </Grid>
  );
}
